apiVersion: apps/v1
kind: Deployment
metadata:
  name: oom-demo
  namespace: akp-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: oom
      app.kubernetes.io/name: oom-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: oom
        app.kubernetes.io/name: oom-demo
    spec:
      containers:
      - name: oom
        image: polinux/stress
        args: ["--vm","1","--vm-bytes","150M","--vm-hang","1"]
        command: ["stress"]
        resources:
          limits:
            cpu: 100m
            memory: 178Mi
          requests:
            cpu: 100m
            memory: 178Mi
        securityContext:
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        startupProbe:
          exec:
            command: ["sleep","5"]
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
